# Generated by Django 2.1.7 on 2019-05-21 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcessoCarro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataEntrada', models.DateField()),
                ('horaEntrada', models.TimeField()),
                ('dataSaida', models.DateField()),
                ('horaSaida', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='AcessoFornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataEntrada', models.DateField()),
                ('horaEntrada', models.TimeField()),
                ('dataSaida', models.DateField()),
                ('horaSaida', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='AcessoMorador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataEntrada', models.DateField()),
                ('horaEntrada', models.TimeField()),
                ('dataSaida', models.DateField()),
                ('horaSaida', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='AcessoVisitante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataEntrada', models.DateField()),
                ('horaEntrada', models.TimeField()),
                ('dataSaida', models.DateField()),
                ('horaSaida', models.TimeField()),
                ('nomeVisitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='painel.CadastroVisitantes')),
            ],
        ),
        migrations.CreateModel(
            name='CadastroCarros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placaCarro', models.CharField(max_length=10)),
                ('modeloCarro', models.CharField(max_length=50)),
                ('corCarro', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CadastroFornecedores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeFornecedor', models.CharField(max_length=100)),
                ('rgFornecedor', models.CharField(max_length=20)),
                ('cpfFornecedor', models.CharField(default='NT', max_length=20)),
                ('descricaoFornecedor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CadastroMorador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeMorador', models.CharField(max_length=100)),
                ('rgMorador', models.CharField(max_length=20)),
                ('enderecoMorador', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='acessomorador',
            name='nomeMorador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='painel.CadastroMorador'),
        ),
        migrations.AddField(
            model_name='acessofornecedor',
            name='nomeFornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='painel.CadastroFornecedores'),
        ),
        migrations.AddField(
            model_name='acessocarro',
            name='placaCarro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='painel.CadastroCarros'),
        ),
    ]
